# Generated by Django 5.2.14 on 2026-05-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_rename_finance_to_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Miqdor (dona, kg, metr va h.k.)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Birlik narxi', max_digits=14),
        ),
        migrations.AlterField(
            model_name='expense',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='month',
            field=models.DateField(unique=True),
        ),
    ]
