# Generated by Django 4.0.8 on 2026-05-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='label',
            field=models.ImageField(blank=True, null=True, upload_to='colors/'),
        ),
    ]
