# Generated by Django 4.0.8 on 2026-05-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_alter_color_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='designcolor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scotchroll',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stonesize',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
