# Generated by Django 4.0.8 on 2026-05-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_color_updated_at_designcolor_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='mold_price_auto',
        ),
    ]
