# Generated by Django 4.2 on 2026-05-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0007_add_moldprice_remove_design_mold_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stonesize',
            name='glass_stone_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shisha tosh narxi', max_digits=10),
        ),
    ]
