# Generated by Django 5.2.14 on 2026-05-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_orders_to_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Buyurtma qilingan dona soni'),
        ),
    ]
