# Generated by Django 4.2 on 2026-05-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_quantity_to_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Qolip narxi (avtomatik hisoblanadi)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Qolip soni (dona)'),
        ),
    ]
